server:
  port: 9001
spring:
  application:
    name: yuehai-demo-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7002/eureka/,http://eureka7001.com:7003/eureka/
  instance:
    instance-id: yuehai-demo-consumer