server:
  port: 9001
spring:
  application:
    name: yuehai-demo-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  #      defaultZone: http://192.168.99.100:7001/eureka/,http://192.168.99.100:7002/eureka/,http://192.168.99.100:7003/eureka/
  instance:
    instance-id: yuehai-demo-consumer